using Avalonia.Controls;
using Avalonia.Interactivity;
using Lpubsppop01.EBookBuilder.App.Services;
using Lpubsppop01.EBookBuilder.App.ViewModels;

namespace Lpubsppop01.EBookBuilder.App.Views;

/// <summary>The dialog for deciding the output settings.</summary>
public partial class BuildDialog : Window
{
    readonly IDialogService m_Dialogs;
    readonly string? m_InitialDirectoryPath;

    public BuildDialog()
    {
        InitializeComponent();
        m_Dialogs = new NullDialogService();
    }

    public BuildDialog(BuildSettings settings, IDialogService dialogs, string? initialDirectoryPath) : this()
    {
        m_Dialogs = dialogs;
        m_InitialDirectoryPath = initialDirectoryPath;
        DataContext = settings;
    }

    // Do not write InitializeComponent by hand.
    // Use the version generated by the XAML compiler (it assigns the x:Name fields).

    async void Browse_Click(object? sender, RoutedEventArgs e)
    {
        if (DataContext is not BuildSettings settings) return;

        var picked = await m_Dialogs.PickSaveFileAsync(
            Path.GetFileName(settings.OutputFilePath), m_InitialDirectoryPath);
        if (picked is not null) settings.OutputFilePath = picked;
    }

    void Ok_Click(object? sender, RoutedEventArgs e) => Close(true);

    void Cancel_Click(object? sender, RoutedEventArgs e) => Close(false);

    /// <summary>A do-nothing implementation for the designer.</summary>
    sealed class NullDialogService : IDialogService
    {
        public Task<bool> ConfirmAsync(string message, string title = "Confirm") => Task.FromResult(false);

        public Task AlertAsync(string message, string title = "EBookBuilder") => Task.CompletedTask;

        public Task<string?> PickSaveFileAsync(string suggestedFileName, string? initialDirectoryPath) =>
            Task.FromResult<string?>(null);
    }
}
