using Avalonia;
using Avalonia.Controls;
using Lpubsppop01.EBookBuilder.App.Settings;
using Lpubsppop01.EBookBuilder.App.ViewModels;

namespace Lpubsppop01.EBookBuilder.App.Views;

/// <summary>The main screen.</summary>
/// <remarks>
/// Only the window's position and size are remembered.
/// The original WPF version used the .NET Framework settings mechanism, but here they are saved as JSON.
/// </remarks>
public partial class MainWindow : Window
{
    readonly AppSettings m_Settings;

    public MainWindow()
    {
        InitializeComponent();
        m_Settings = new AppSettings();
    }

    public MainWindow(MainViewModel viewModel, AppSettings settings) : this()
    {
        m_Settings = settings;
        DataContext = viewModel;

        Width = settings.WindowWidth;
        Height = settings.WindowHeight;
    }

    // Do not write InitializeComponent by hand.
    // Use the version generated by the XAML compiler (it assigns the x:Name fields).

    protected override void OnOpened(EventArgs e)
    {
        base.OnOpened(e);

        // Going off-screen would make the window impossible to operate, so the previous
        // position is only restored when it is safe to do so.
        if (m_Settings.WindowX is { } x && m_Settings.WindowY is { } y)
        {
            var saved = new PixelPoint(x, y);
            if (Screens.ScreenFromPoint(saved) is not null) Position = saved;
        }
    }

    protected override void OnClosing(WindowClosingEventArgs e)
    {
        base.OnClosing(e);

        // Saving the dimensions from a maximized or minimized state would make the window
        // open at a strange size next time.
        if (WindowState == WindowState.Normal)
        {
            m_Settings.WindowWidth = Width;
            m_Settings.WindowHeight = Height;
            m_Settings.WindowX = Position.X;
            m_Settings.WindowY = Position.Y;
        }

        m_Settings.Save();
    }
}
